### ISSUE TITLE
developer payment approval

### ISSUE THREAD

**Issue by papes11** [pi-apps/demo#45]
how do I approve payment from users
Because when I test the app and try to pay it keeps saying waiting for developers approval and it doesn't end up approving until time out .. How do I fix this???need in details

**Comment by coolmanAK47** [comment]
just copy the codes from users/login into payments/approve for a quick fix

**Comment by coolmanAK47** [comment]
@papes11 The issue is with express session and browser cookie. If you deploy the codes with docker onto a VPS, you can log some messages in the console to see that the backend payment approval method is failing because of req.session.currentUser is not returning anything (at least for my case).

The work around for me (force the user to login again and assign a value to req.session.currentUser in the current route):
// approve the current payment
router.post('/approve', async (req, res, next) => {
    console.log("approve payment");
    if (req.session) {
      console.log("session is okay");
      console.log(req.session.currentUser);
    }

    if (!req.session.currentUser) {
      console.log("no currentUser");

      const auth = req.body.authResult;
      const userCollection = req.app.locals.userCollection;

      try {
        // Verify the user's access token with the /me endpoint:
        const me = await platformAPIClient.get(`/v2/me`, { headers: { 'Authorization': `Bearer ${auth.accessToken}` } });
        console.log(me);
      } catch (err) {
        console.log(err);
        return res.status(401).json({ error: "Invalid access token" })
      }

      let currentUser = await userCollection.findOne({ uid: auth.user.uid });

      if (currentUser) {
        await userCollection.updateOne({
          _id: currentUser._id
        }, {
          $set: {
            accessToken: auth.accessToken,
          }
        });
      } else {
        const insertResult = await userCollection.insertOne({
          username: auth.user.username,
          uid: auth.user.uid,
          roles: auth.user.roles,
          accessToken: auth.accessToken
        });

        currentUser = await userCollection.findOne(insertResult.insertedId);
      }

      req.session.currentUser = currentUser;

      if (!req.session.currentUser) {
        console.log("backend session not okay...");
        return res.status(401).json({ error: 'unauthorized', message: "User needs to sign in first" });
      } else {
        console.log("backend session okay...");
        console.log(req.session.currentUser.username + " logged in");
      }
      // return res.status(401).json({ error: 'unauthorized', message: "User needs to sign in first" });
    }

Note: I have tried to use universal-cookie, react-cookie, and etc. but no luck, I have even tried to change using cookie with express session instead of MongoDB as store.

**Comment by papes11** [comment]
> 

thanks for the help man but n0 luck pi dev sholud look into express once ..

**Comment by coolmanAK47** [comment]
Don't forget to edit the frontend (index.tsx) to pass in authResult as well, because the change I make for /payments/approve route will now require Pi's API to verify your logged in user every time when someone tries to make a purchase.

  const onReadyForServerApproval = async (paymentId: string) => {
    console.log("onReadyForServerApproval", paymentId);
    const scopes = ['username', 'payments'];
    const authResult: AuthResult = await window.Pi.authenticate(scopes, onIncompletePaymentFound);
    axiosClient.post('/payments/approve', { paymentId, authResult }, config)
      .then(response => {
        console.log(response);
      }).catch(e => {
        console.log(e);
      });
  }

I wonder if session and cookie actually works in Pi Browser.

**Comment by papes11** [comment]
> Don't forget to edit the frontend (index.tsx) to pass in authResult as well, because the change I make for /payments/approve route will now require Pi's API to verify your logged in user every time when someone tries to make a purchase.
> 
> const onReadyForServerApproval = async (paymentId: string) => { console.log("onReadyForServerApproval", paymentId); const scopes = ['username', 'payments']; const authResult: AuthResult = await window.Pi.authenticate(scopes, onIncompletePaymentFound); axiosClient.post('/payments/approve', { paymentId, authResult }, config) .then(response => { console.log(response); }).catch(e => { console.log(e); }); }
> 
> I wonder if session and cookie actually worked in Pi Browser.

thanks mate i was checking up
